version: '2'

services:
  demo-board:
    build: .
    image: demo-board
    restart: unless-stopped
    privileged: true
    network_mode: 'host'
    devices:
      - "/dev/ttyUSB*:/dev/ttyUSB*" 
    environment:
      - DEMO_BOARD_TYPE=2
      - STARTUP_DATE=20210121 10:00:00