{
 "title": "draft dashboard",
 "time": { "from": "2021-06-05T10:53:18.072Z", "to": "2021-06-05T10:55:23.148Z" },
 "panels": [
  {
   "title": "M11 power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  powermin as redmin,\n  powersma as redsma,\n  powermax as redmax\nFROM fake_data\nWHERE devicename = 'M11'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "M31 power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  powermin as redmin,\n  powersma as redsma,\n  powermax as redmax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 0\nORDER BY 1"
    },
    {
     "rawSql": "select\n  time,\n  powermin as whitemin,\n  powersma as whitesma,\n  powermax as whitemax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 1\nORDER BY 1"
    },
    {
     "rawSql": "select\n  time,\n  powermin as bluemin,\n  powersma as bluesma,\n  powermax as bluemax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "M11 voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  voltagemin as redmin,\n  voltagesma as redsma,\n  voltagemax as redmax\nFROM fake_data\nWHERE devicename = 'M11'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "M31 voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  voltagemin as redmin,\n  voltagesma as redsma,\n  voltagemax as redmax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 0\nORDER BY 1"
    },
    {
     "rawSql": "select\n  time,\n  voltagemin as whitemin,\n  voltagesma as whitesma,\n  voltagemax as whitemax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 1\nORDER BY 1"
    },
    {
     "rawSql": "select\n  time,\n  voltagemin as bluemin,\n  voltagesma as bluesma,\n  voltagemax as bluemax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select\n  time,\n  type,\n  devicename\nFROM fake_alarms\nORDER BY 1"
    }
   ]
  },
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "M11 current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  currentmin as redmin,\n  currentsma as redsma,\n  currentmax as redmax\nFROM fake_data\nWHERE devicename = 'M11'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "M31 current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  currentmin as redmin,\n  currentsma as redsma,\n  currentmax as redmax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 0\nORDER BY 1"
    },
    {
     "rawSql": "select\n  time,\n  currentmin as whitemin,\n  currentsma as whitesma,\n  currentmax as whitemax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 1\nORDER BY 1"
    },
    {
     "rawSql": "select\n  time,\n  currentmin as bluemin,\n  currentsma as bluesma,\n  currentmax as bluemax\nFROM fake_data\nWHERE devicename = 'M31' AND phase = 2\nORDER BY 1"
    }
   ]
  }
 ]
}